// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rn70mMY6gXselE4zvRljlkEqm-dgw_k',
    appId: '1:810987198941:android:38190c5790e7ac7f3cbe34',
    messagingSenderId: '810987198941',
    projectId: 'babysitter4b-b3fe2',
    storageBucket: 'babysitter4b-b3fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKRZfaF-rciCt4ArCrRWf_d4_hw84PXl0',
    appId: '1:810987198941:ios:b40b4b2da73ff74c3cbe34',
    messagingSenderId: '810987198941',
    projectId: 'babysitter4b-b3fe2',
    storageBucket: 'babysitter4b-b3fe2.firebasestorage.app',
    androidClientId: '810987198941-j5fv2odslnehorf5hj8dd3jp62n5007r.apps.googleusercontent.com',
    iosClientId: '810987198941-5135n15ls5rts6joklvod3ghcusvnf7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.babysitterapp',
  );
}
